/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rkaune
 */
public class Newfrm extends javax.swing.JFrame {

    /**
     * Creates new form Newfrm
     */
    public Newfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUIpnl = new javax.swing.JPanel();
        Promptlbl = new javax.swing.JLabel();
        PressMebtn = new javax.swing.JButton();
        Nametxt = new javax.swing.JTextField();
        Outputlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GUIpnl.setBackground(new java.awt.Color(255, 255, 255));
        GUIpnl.setForeground(new java.awt.Color(255, 51, 0));

        Promptlbl.setText("Enter your name");

        PressMebtn.setText("Press me!");
        PressMebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PressMebtnActionPerformed(evt);
            }
        });

        Outputlbl.setText("Message goes here");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Pictures\\Exercise.png")); // NOI18N

        javax.swing.GroupLayout GUIpnlLayout = new javax.swing.GroupLayout(GUIpnl);
        GUIpnl.setLayout(GUIpnlLayout);
        GUIpnlLayout.setHorizontalGroup(
            GUIpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIpnlLayout.createSequentialGroup()
                .addGroup(GUIpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUIpnlLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Promptlbl)
                        .addGap(29, 29, 29)
                        .addComponent(Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GUIpnlLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(PressMebtn))
                    .addGroup(GUIpnlLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(Outputlbl))
                    .addGroup(GUIpnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GUIpnlLayout.setVerticalGroup(
            GUIpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIpnlLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(GUIpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Promptlbl)
                    .addComponent(Nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(PressMebtn)
                .addGap(38, 38, 38)
                .addComponent(Outputlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUIpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUIpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PressMebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PressMebtnActionPerformed
        String name = "";
        name = Nametxt.getText();
        Outputlbl.setText("Hello " + name + "!");
    }//GEN-LAST:event_PressMebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GUIpnl;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JLabel Outputlbl;
    private javax.swing.JButton PressMebtn;
    private javax.swing.JLabel Promptlbl;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
